DATASET:
  MEAN: 0.1307
  STD: 0.3081
  PATH: datasets/cifar10_os/data_fold_%s.pkl
  TOTAL_CLASS_COUNT: 10
  FOLDS_COUNT: 5
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: False
  OFFICIAL_SPLIT: True
MODEL:
  LATENT_SPACE_SIZE: 64
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 128
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  INPUT_IMAGE_CHANNELS: 3
OUTPUT_DIR: cifar10_os_results
RESULTS_NAME: results.csv
ALPHA_BETA_TUNING: True
TRAIN:
  BASE_LEARNING_RATE: 0.002
  LEARNING_RATES: 0.002
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 460
  BATCH_1GPU: 64

THRESHOLD_NARROW_WINDOW: (-1000, 1000)
THRESHOLD_FINAL_WINDOW: (-10000, 10000)
