DATASET:
  PATH: datasets/coil100/data_fold_%d.pkl
  TOTAL_CLASS_COUNT: 100
  FOLDS_COUNT: 5
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: True
  PERCENTAGES: [50, 25, 15]
  MIX_VALIDATION_AND_TRAINING: True
  # TRAIN_MUL: 100
MODEL:
  LATENT_SPACE_SIZE: 32
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  INPUT_IMAGE_CHANNELS: 3
OUTPUT_DIR: coil100_results
RESULTS_NAME: results.csv
# ALPHA_BETA_TUNING: True
ALPHA_BETA_TUNING: False
ALPHA: 13.0
BETA: 0.4
TRAIN:
  BASE_LEARNING_RATE: 0.002
  LEARNING_RATES: 0.002
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 70
  BATCH_1GPU: 64

THRESHOLD_NARROW_WINDOW: (-10000, 10000)
THRESHOLD_FINAL_WINDOW: (-10000, 10000)
