DATASET:
  MEAN: 0.1307
  STD: 0.3081
  PATH: datasets/covid/aligned_data_%s.pkl
  TOTAL_CLASS_COUNT: 10
  FOLDS_COUNT: 5
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: False
  OFFICIAL_SPLIT: True
  COVID: True
  OUTLIER: 2
  PERCENTAGES: [50]
MODEL:
  INPUT_IMAGE_SIZE: 128
  LATENT_SPACE_SIZE: 64
  LAYER_COUNT: 6
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 32
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  INPUT_IMAGE_CHANNELS: 1
OUTPUT_DIR: covid_results
RESULTS_NAME: results.csv
ALPHA_BETA_TUNING: True
TRAIN:
  BASE_LEARNING_RATE: 0.002
  LEARNING_RATES: 0.002
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 160
  BATCH_1GPU: 32

TEST:
  BATCH_SIZE: 64

THRESHOLD_NARROW_WINDOW: (-1000, 1000)
THRESHOLD_FINAL_WINDOW: (-10000, 10000)
