DATASET:
  MEAN: 0.1307
  STD: 0.3081
  PATH: datasets/mnist/data_fold_%d.pkl
  TOTAL_CLASS_COUNT: 10
  FOLDS_COUNT: 5
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: False
MODEL:
  LATENT_SPACE_SIZE: 16
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  CHANNELS: 1
OUTPUT_DIR: mnist_results
TRAIN:
  BASE_LEARNING_RATE: 0.002
  LEARNING_RATES: 0.0015
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 75
  BATCH_1GPU: 128
